# -*- coding: utf-8 -*-
"""인기검색어 크롤링.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vEGTvL5kmMh-zTjhvosRWGC_pFcV5Ntd
"""

import requests, json
from bs4 import BeautifulSoup as bs
from datetime import datetime
import csv

#네이트 실시간 검색어 크롤링
now = datetime.now().strftime('%Y%m%d%H%M')
url = 'https://www.nate.com/js/data/jsonLiveKeywordDataV1.js?v=' + now
r = requests.get(url).content
keyword_list = json.loads(r.decode('euc-kr'))
nate_result = []
for k in keyword_list:
    nate_result.append(k[1])
with open("nate_trends.csv", 'w') as file: 
  writer = csv.writer(file) 
  writer.writerow(nate_result)

#줌 실시간 검색어 크롤링
url = 'https://m.search.zum.com/search.zum?method=uni&option=accu&qm=f_typing.top&query='
html = requests.get(url).content
soup = bs(html, 'html5lib')
keyword_list = soup.find('div', {'class' : 'list_wrap animate'}).find_all('span', {'class' : 'keyword'})
zum_result = []
for k in keyword_list:
    zum_result.append(k.text.strip())

with open("zum_trends.csv", 'w') as file: 
  writer = csv.writer(file) 
  writer.writerow(zum_result)

#구글 트랜드 사용을 위해 pytrends 설치
!pip install pytrends 


#구글 트랜드 일간 인기 검색어 가져오기
from pytrends.request import TrendReq
import pandas as pd
pytrends = TrendReq(hl="ko", tz=360)
pytrends.trending_searches(pn='south_korea')

#네이트 실시간 검색어 크롤링
now = datetime.now().strftime('%Y%m%d%H%M')
url = 'https://www.nate.com/js/data/jsonLiveKeywordDataV1.js?v=' + now
r = requests.get(url).content
keyword_list = json.loads(r.decode('euc-kr'))
nate_result = []
for k in keyword_list:
    nate_result.append(k[1])
with open("nate_trends.csv", 'w') as file: 
  writer = csv.writer(file) 
  writer.writerow(nate_result)

#줌 실시간 검색어 크롤링
url = 'https://m.search.zum.com/search.zum?method=uni&option=accu&qm=f_typing.top&query='
html = requests.get(url).content
soup = bs(html, 'html5lib')
keyword_list = soup.find('div', {'class' : 'list_wrap animate'}).find_all('span', {'class' : 'keyword'})
zum_result = []
for k in keyword_list:
    zum_result.append(k.text.strip())

with open("zum_trends.csv", 'w') as file: 
  writer = csv.writer(file) 
  writer.writerow(zum_result)

#csv 파일로 변환 
import pandas as pd

zum_df = pd.read_csv("zum_trends.csv")
zum_df = zum_df.transpose()
zum_df = zum_df.reset_index()
zum_df

nate_df = pd.read_csv("nate_trends.csv")
nate_df = nate_df.transpose()
nate_df = nate_df.reset_index()
nate_df

#구글 트랜드 사용을 위해 pytrends 설치
!pip install pytrends

#구글 트랜드 일간 인기 검색어 가져오기
from pytrends.request import TrendReq
import pandas as pd
pytrends = TrendReq(hl="ko", tz=360)
pytrends = pytrends.trending_searches(pn='south_korea')
pytrends.to_csv("google_trends.csv", mode = 'w', index = None)

# 
#